package interfaz;

import dominio.AdminAcademica;
import dominio.AdminAdministrativa;
import dominio.Sistema;

public class frmMenu extends javax.swing.JFrame {
    AdminAcademica academ;
    AdminAdministrativa admin;
    
    public frmMenu() {
        initComponents();
    }
    
    public frmMenu(AdminAcademica academ, AdminAdministrativa admin) {
        initComponents();
        this.academ = academ;
        this.admin = admin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuEst = new javax.swing.JMenu();
        mnuAltaEst = new javax.swing.JMenuItem();
        mnuEstExm = new javax.swing.JMenuItem();
        mnuDoc = new javax.swing.JMenu();
        mnuAltaDoc = new javax.swing.JMenuItem();
        mnuMat = new javax.swing.JMenu();
        mnuAltaMat = new javax.swing.JMenuItem();
        mnuExm = new javax.swing.JMenu();
        mnuAltaExm = new javax.swing.JMenuItem();
        mnuActaExm = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuEst.setText("Estudiantes");

        mnuAltaEst.setText("Alta Estudiante");
        mnuAltaEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAltaEstActionPerformed(evt);
            }
        });
        mnuEst.add(mnuAltaEst);

        mnuEstExm.setText("Inscribir a Examen");
        mnuEst.add(mnuEstExm);

        jMenuBar1.add(mnuEst);

        mnuDoc.setText("Docentes");

        mnuAltaDoc.setText("Alta Docente");
        mnuDoc.add(mnuAltaDoc);

        jMenuBar1.add(mnuDoc);

        mnuMat.setText("Materias");

        mnuAltaMat.setText("Alta Materia");
        mnuMat.add(mnuAltaMat);

        jMenuBar1.add(mnuMat);

        mnuExm.setText("Examenes");

        mnuAltaExm.setText("Alta Examen");
        mnuExm.add(mnuAltaExm);

        mnuActaExm.setText("Acta Examen");
        mnuExm.add(mnuActaExm);

        jMenuBar1.add(mnuExm);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAltaEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAltaEstActionPerformed
        frmEstudiantes frm = new frmEstudiantes();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuAltaEstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuActaExm;
    private javax.swing.JMenuItem mnuAltaDoc;
    private javax.swing.JMenuItem mnuAltaEst;
    private javax.swing.JMenuItem mnuAltaExm;
    private javax.swing.JMenuItem mnuAltaMat;
    private javax.swing.JMenu mnuDoc;
    private javax.swing.JMenu mnuEst;
    private javax.swing.JMenuItem mnuEstExm;
    private javax.swing.JMenu mnuExm;
    private javax.swing.JMenu mnuMat;
    // End of variables declaration//GEN-END:variables
}
